### ISSUE TITLE
There is no simple way to clear form collection if form is bound to an object.

### ISSUE THREAD

**Issue by Redigast13** [zendframework/zendframework#7298]
I use doctrine 2 with ZF2 forms. When I submit a form I bind doctrine entity to the form. Then I set POST data to the form. And if the form is valid I save the data to DB. I think it is a normal way to work with ZF2 forms. I use this code when user wants to update "user" entity.
```
// $form has form collection "roles"
$form->bind($entity); // $entity->roles is not empty
$form->setData($someData); // $someData['roles'] is empty array
if ($form->isValid()) {
    $form->get('roles')->getCount(); // 2(!) it is not empty!
    saveToDb($entity);
}
return $form;
```
Do you think that this code is corrrect? No. Because there is a form collection in this form. And $entity has two roles now. And user wants to remove all roles from "user" entity. And this beautiful framework can't clear form collection. (populateValues() does nothing if data is empty https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element/Collection.php#L199 )

So, what should I do? I should find all form collections in this form and clear this collection in doctrine entity before I bind this entity to the form.
```
foreach ($form->getFieldsets() as $fieldset) {
    if ($fieldset instanceof Collection) {
        $name = $fieldset->getName();
        if (empty($someData[$name])) {
            $methodName = 'set' . ucfirst($name);
            call_user_func([$entity, $methodName], []);
        }
    }
}
$form->bind($entity); // now $entity->roles is empty
$form->setData($someData); // $someData['roles'] is empty array
if ($form->isValid()) {
    $form->get('roles')->getCount(); // 0
    saveToDb($entity);
}
return $form;
```
Very elegant! Here is the same issue https://github.com/zendframework/zf2/issues/4492 . It opened TWO years ago. What happened with ZF2? Is this project dead?

**Comment by sandrokeil** [comment]
Hello @Redigast13 , I've worked with Doctrine 2 and form collections (fieldsets) and had no issues. Do you use the `DoctrineModule\Stdlib\Hydrator\DoctrineObject` in your fieldset? Here is a fieldset example. The verifier (Account table) is optional and can be null. Must be defined in your database table. Doctrine does the rest.

```php
    public function init()
    {
        $this->setHydrator(new \DoctrineModule\Stdlib\Hydrator\DoctrineObject($this->getObjectManager(), false));
        // bind entity to form
        $this->setObject(new Bug());

        // some more stuff

        $this->add($this->getElementVerifiedBy());

        parent::init();
    }

    protected function getElementVerifiedBy()
    {
        return array(
            'type' => 'DoctrineORMModule\Form\Element\EntitySelect',
            'name' => 'verifiedBy',
            'attributes' => array('id' => 'verifier',),
            'options' => array(
                'label' => 'verifier',
                'empty_option' => 'Please choose verifier',
                'object_manager' => $this->getObjectManager(),
                'target_class' => 'Account',
                'property' => 'username' // property name for option value
            )
        );
    }

```

The method `$this->getObjectManager()`returns an instance of `\Doctrine\Common\Persistence\ObjectManager``.

**Comment by Redigast13** [comment]
Hello @sandrokeil . Yes, I use DoctrineModule\Stdlib\Hydrator\DoctrineObject. But it is not a fieldset. It is a form collection (Zend\Form\Element\Collection). The problem is that I can't clear collection if there is already some data in the collection. For example:
```
$form->setData(['roles' => ['admin', 'moderator]]); // form collection "roles" will have two items
$form->setData(['roles' => []]); // form collection "roles" still has two items
```
It happens bacause of populateValues() method does nothing if data is empty https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element/Collection.php#L199

In ZF2 if I want to bind an object to the form I should bind it before I set data to the form from $_POST array. In my case the entity object already has some value in collection.
When I do `$form->bind($entity) ` I set some data to the form collection. Then I do $form->setData(['roles' => []]) And form collection still has value. 
For example user wants to remove all roles. He removes all roles in the form and submits data. Then he see the form with roles again. This is a problem.

**Comment by sandrokeil** [comment]
Hmm, but on the [form collection element page](http://framework.zend.com/manual/current/en/modules/zend.form.elements.html#collection) is a link to the [form collections aka fieldsets page](http://framework.zend.com/manual/current/en/modules/zend.form.collections.html#zend-form-collections). You have 2 entities user and role, which is the same (entity bug and user) from my example above. I think you have to use a form fieldset. The [Doctrine form element](https://github.com/doctrine/DoctrineORMModule/tree/master/src/DoctrineORMModule/Form/Element) handles the values.

**Comment by Redigast13** [comment]
In your example one Bug has one user (verifier), right? In my example one user has many roles.
Zend\Form\Fieldset is just a group of fields.
Zend\Form\Collection extends Zend\Form\Fieldset. In collection I can add and remove elements dynamically. So, I need exactly Zend\Form\Collection because I need to add and remove roles from user.

**Comment by sandrokeil** [comment]
Yes, you're right. But a bug can have multiple products with select option multiple. With this I can add/remove multiple products from bug. But it's a select element. I've never tried the collection element. Maybe other users can help you.

```php
    protected function getElementProduct()
    {
        return array(
            'type' => 'DoctrineORMModule\Form\Element\EntitySelect',
            'name' => 'product',
            'attributes' => array(
                'id' => 'product',
                'multiple' => true // <-- one or more
            ),
            'options' => array(
                'label' => 'product',
                'empty_option' => 'Please choose product',
                'object_manager' => $this->getObjectManager(),
                'target_class' => 'Product',
                'property' => 'name' // property name for option
            )
        );
    }
```

**Comment by Redigast13** [comment]
Anyway thank you. Multiple select will really solve this problem. But it was a simple example. If I had text field or group of fields that should dynamically add or remove then I would need form collection. And it is very sad that ZF2 developers don't solve this issue for two years. (https://github.com/zendframework/zf2/issues/4492)

**Comment by svycka** [comment]
this is not fixed after 2 years.. 2.4.0 still have this bug
seems like there is a test for this https://github.com/zendframework/zf2/blob/6002c348ee9ebad645654bfd8e5a4f64b69c5fbe/tests/ZendTest/Form/Element/CollectionTest.php#L933-L948
but it does not fail. @weierophinney maybe you can take a look at this. I think you merged this.

**Comment by svycka** [comment]
fixed with https://github.com/zendframework/zend-form/pull/14

**Comment by write2art** [comment]
[zendframework/zend-form#14](http://example.com/ "zendframework/zend-form#14") does not fix the issue, cause it lies deeper, in the Form::prepareBindData() method:

```php
protected function prepareBindData(array $values, array $match)
{
    $data = [];
    foreach ($values as $name => $value) {
        if (!array_key_exists($name, $match)) {
            continue;
        }

        if (is_array($value) && is_array($match[$name])) {
            $data[$name] = $this->prepareBindData($value, $match[$name]);
        } else {
            $data[$name] = $value;
        }
    }
    return $data;
}
```

$match - is a data came from post. And if it does not contain empty array (which is impossible to accomplish without altering post data manually before $form->setData($post)) the collection will not be cleared.

**Comment by svycka** [comment]
I think there is one more issue when empty collection is not passed to hydrator so it does not get hydrated.

**Comment by write2art** [comment]
If an empty array for a collection presents in a post data it hydrates normally, clearing the collection.

**Comment by svycka** [comment]
@write2art would https://github.com/zendframework/zend-form/pull/19 fix your problem?

**Comment by write2art** [comment]
@svycka nope. As i mentioned before, all data which is not present in post data gets filtered in Form::prepareBindData() method.

**Comment by svycka** [comment]
prepareBindData() descriptions says
> Parse filtered values and return only posted fields for binding

so it works correctly I think.

also added test to check your usecase and it seems it passed so what exactly does not work? Maybe my test doesn't cover what you need?

**Comment by svycka** [comment]
@write2art yes I know that, but I fixed it elsewhere and added test. Also just tested with doctrine hydrator also works for me. Can you show how you testing it?

**Comment by write2art** [comment]
@svycka Form/Element/Collection overides fieldset bindValues() method, so i really don`t think this fix should alert it in anyway.

My test is not a test actually, it`s an app prototype, so i can`t paste only the collection part here, but i can describe it. I`m using standard (almost from collection docs) setup. I have a product entity which has keywords (my collection). Here is the element declaration:

```php
        $this->add([
            'type' => 'Collection',
            'name' => 'keywords',
            'options' => [
                'count' => 0,
                'should_create_template' => true,
                'allow_add' => true,
                'target_element' => [
                    'type' => 'ProductKeyword'
                ],
            ],
        ]);
```

Nothing unusual here.

Here is the ProductKeyword fieldset:
```php
class KeywordFieldset extends Fieldset implements ObjectManagerAwareInterface
{
    use ProvidesObjectManager;

    public function init()
    {
        $this
            ->setName('ProductKeyword')
            ->setHydrator(new DoctrineObject($this->getObjectManager()))
            ->setObject(new ProductKeyword());

        $this->add([
            'type' => 'Hidden',
            'name' => 'id',
            'attributes' => [
                'class' => 'i-id'
            ]
        ]);

        $this->add([
            'type' => 'Text',
            'name' => 'name',
            'attributes' => [
                'class' => 'i-name'
            ]
        ]);
    }

    public function getInputFilterSpecification()
    {
        return [
            'id' => [
                'required' => false,
                'filters' => [
                    ['name' => 'ToNull']
                ],
                'validators' => [
                ],
            ],
            'name' => [
                'required' => true,
                'filters' => [
                    ['name' => 'ToNull'],
                    ['name' => 'StringTrim'],
                    ['name' => 'StringToLower', 'options' => ['encoding' => 'UTF-8']],
                ],
                'validators' => [
                    ['name' => 'StringLength', 'options' => ['max' => 50]],
                ],
            ],
        ];
    }

}
```

It adds and removes keywords just fine. The only issue is when i try to remove all keywords. I`m doing it through js - just removing and adding form elements from page. When all keywords are removed, this collection is not present in the post data, which results in filtering out this key from bind values in Form::prepareBindData(). If i manually add an empty array to post data just before calling the $form->setData(), everything works fine - my collection gets cleared. 

I`m not stating that Form::prepareBindData()  works incorrectly - it`s doing just what it should. But it seems that there is no way to remove all element from collection with this behavior. 

Could you please describe the scenario in which your tests are working? May be it is simpler to refactor my app, than to fix zf :)

**Comment by svycka** [comment]
@write2art  don't know why it does not work for you. As you can see I didn't do anything special in the test. Just created form with fieldset and collection then binded object with two items and  https://github.com/zendframework/zend-form/pull/19/files#diff-c8ff4535f5e8cabfe21dd0dd59e9e02cR2166 here I did not add `foo` collection like you said, $_POST doesn't have it and collection in the end is cleared.  Are you using this https://github.com/zendframework/zend-form/pull/19 with your app?

**Comment by write2art** [comment]
@svycka me don't know either - my setup looks just the same as yours. But the fact is - if empty array presents in the post data, collection gets cleared. Otherwise, not. And yes, i'm using [#19](https://github.com/zendframework/zend-form/pull/19).

By the way, can you please check, does your test for [#19](https://github.com/zendframework/zend-form/pull/19) passes without [#19](https://github.com/zendframework/zend-form/pull/19) fix?

**Comment by svycka** [comment]
@write2art no it doesn't

**Comment by valeeum** [comment]
I'm having the same exact issue.    Can not remove last item in collection.

**Comment by berturion** [comment]
Same thing here. Can not emty any collection since there is at least one element. This is by far the worst issue I ever saw on this framework. I think it should be treated at top priority.

**Comment by FabianKoestring** [comment]
I think they are working on that problem!

https://github.com/zendframework/zend-form/pull/19

**Comment by FabianKoestring** [comment]
> Same thing here. Can not emty any collection since there is at least one element. This is by far the worst issue I ever saw on this framework. I think it should be treated at top priority.

Same here. Cant understand that this problem still exists. :cry:

**Comment by Ocramius** [comment]
Can this be isolated with a test case? As already mentioned, work around this was done in #19, so if nobody provides an actual test scenario this is going to be closed as "can't reproduce"

**Comment by svycka** [comment]
@FabianKoestring  I think this is fixed with https://github.com/zendframework/zend-form/pull/19 or this still does not work? Did you tested with latest version?

**Comment by FabianKoestring** [comment]
@svycka Yea i tested with that fix.I hoped that your fix would work but this issue still exists.

**Comment by weierophinney** [comment]
@FabianKoestring Then what we need for you to do is:

- Create a new issue on [zend-form](https://github.com/zendframework/zend-form/issues)
- In that issue:
  - Provide a concise reproduce case that demonstrates the issue.
  - Detail what you expect (ideally, using code to demonstrate the expected behavior).
  - Detail what you actually observe.

At this point, we've had several patches that should fix the behavior, and without your specific reproduce case, we cannot investigate further.

**Comment by svycka** [comment]
@FabianKoestring there is a test for this https://github.com/svycka/zend-form/blob/82b0cdcad2be8313f78bc53eb4d775fc243281cf/test/FormTest.php#L2162-L2195 unless I did something wrong everything should work or maybe you can show us what you do differently.

**Comment by FabianKoestring** [comment]
@svycka Yea i know. I run that test locally and its green. The only difference i can see is that iam using `\DoctrineModule\Stdlib\Hydrator\DoctrineObject` instead of `\Zend\Hydrator\ObjectProperty()`.

**Comment by svycka** [comment]
@FabianKoestring just tested with `DoctrineModule\Stdlib\Hydrator\DoctrineObject` also works. Maybe problem somewhere else in your code? @FabianKoestring can you do as @weierophinney said because for me works with zend hydrator and with doctrineObject hydrator.

**Comment by FabianKoestring** [comment]
Ok i think i found the problem. I had this issue on a few projects. The ones where i used fieldsets are working as expected after fix of @svycka. The one i was testing right now had  no fieldset, it used `DoctrineModule\Form\Element\ObjectSelect`.

```php
$objectSelect = new ObjectSelect('objectSelect');
$objectSelect->setLabel('objectSelect');
$objectSelect->setAttribute('multiple', true);
$objectSelect->setOptions(
    [
        'object_manager'     => $entityManager,
        'target_class'       => Entity\Test::class,
        'display_empty_item' => true,
        'empty_item_label'   => 'Please select element.'
    ]
);
$this->add($objectSelect);
```

There is a similar problem. I will debug into it and will report a bug there if nessecary.

**Comment by FabianKoestring** [comment]
Just for people who have the same problem. `$objectSelect ->setUseHiddenElement(true);` fixed it.

I think this can be closed but iam not the creator of the issue.
